#!/usr/bin/env python3
"""5-seed Tier-1 baseline reproduction for paper §5.1.

Reproduces the 9 truly-unsupervised baselines × 5 heterophilic datasets ×
5 random seeds = 225 runs that the paper §5.1 main comparison table claims
to report ("All values are mean over 5 seeds" — paper_cee.tex:572).

The previous 3-seed run lives at
``experiments/sheaf_curvature_001/results/baselines_NMI_tier1.csv`` and was
generated by ``experiments/run_tier1_protocol.py``. This script extends that
protocol to seeds [0, 1, 2, 3, 4] and writes a fresh CSV so the canonical
"5 seeds" claim in §5.1 has on-disk provenance.

Output
------
Default: ``results/baselines_NMI_5seed.csv`` (225 rows).
Override with env var ``BASELINES_5SEED_OUT``.

Dependencies
------------
- ``experiments/baselines_official.py`` (1067 LOC) provides the 9 wrappers
  registered in ``BASELINE_REGISTRY`` and the run helpers ``run_louvain``,
  ``run_leiden``, ``run_spectral``, ``run_dmon``, ``run_vgraph``,
  ``run_agc``, ``run_dgi``, ``run_grace``, ``run_graphmae``.
- ``experiments/dmon_mincut.py`` provides ``load_extended`` (the dataset
  loader used by every wrapper).
- ``experiments/unified_eval.py`` provides ``evaluate_nmi`` /
  ``evaluate_nmi_from_assignment``.
- ``/home/woody/workspace/ARC/baselines/vGraph/`` (cloned vGraph repo).
  The hard-coded ``BASELINES`` absolute path inside ``baselines_official.py``
  resolves this; ``vGraph/model.py`` is the only Tier-1 external-repo import.

This script does not vendor the upstream wrappers into ``cgsd`` on
purpose: vendoring 1000+ LOC just to add ``seeds = [0..4]`` would inflate
the open-source release without adding reproducible signal. The dependency
is documented here and in the README so that anyone running
``bash reproduce.sh`` for canonical CGSD is unaffected — this script is an
*optional* supplementary reproduction, not part of the canonical path.

Expected runtime
----------------
Single RTX 2060 (6 GB), 12 CPU cores. Past 3-seed run completed 135 runs in
~2.5 min; this 225-run script is expected to finish in 4–6 min.
"""
from __future__ import annotations

import csv
import os
import sys
import time
import warnings
from pathlib import Path
from typing import Any

warnings.filterwarnings("ignore")

# --------------------------------------------------------------- paths ----
# scripts/run_baselines_5seed.py
_HERE = Path(__file__).resolve().parent                              # .../cgsd/scripts/
_REPO_ROOT = _HERE.parent                                             # .../cgsd/ (repo root)
# experiments/baselines_official.py
# (the wrappers live in the sibling `experiments/` of the repo root).
_EXPERIMENTS = _REPO_ROOT.parent / "experiments"
# Default output CSV inside results/ (matches run_sbm_sweep.py).
_DEFAULT_OUT = _REPO_ROOT / "results" / "baselines_NMI_5seed.csv"

# The wrappers live in experiments/ — add it to sys.path so the bare
# `from baselines_official import ...` and `from dmon_mincut import ...`
# imports inside baselines_official.py resolve correctly.
sys.path.insert(0, str(_EXPERIMENTS))

# Verified-by-audit imports; the wrappers and dataset loader are unchanged
# from the existing 3-seed protocol. The wrappers themselves use sys.path
# injection (baselines_official.py:46-50) for the cloned vGraph repo.
from baselines_official import TIER1_KEYS, BASELINE_REGISTRY  # noqa: E402

# ----------------------------------------------------------------- cfg ----
DATASETS = ["Cora", "Cornell", "Texas", "Wisconsin", "Chameleon"]
SEEDS = [0, 1, 2, 3, 4]  # 5 seeds, matching paper §5.1 caption
EPOCHS = 200
OUT_CSV = Path(os.environ.get("BASELINES_5SEED_OUT", str(_DEFAULT_OUT)))
CSV_COLUMNS = [
    "method", "dataset", "seed",
    "nmi", "ari", "fmi", "homo", "compl", "v_measure", "runtime_s",
]


# ------------------------------------------------------------- helpers ----
def _load_extended(name: str):
    """Re-export of ``dmon_mincut.load_extended`` (avoids duplicating code).

    The 5 datasets here are exactly those supported by the upstream loader
    (Cora / Cornell / Texas / Wisconsin / Chameleon). See
    ``experiments/dmon_mincut.py:43-87`` for the canonical implementation.
    """
    from dmon_mincut import load_extended  # local import for symmetry
    return load_extended(name)


def _evaluate_nmi_from_assignment(labels, assignment):
    """Re-export of ``unified_eval.evaluate_nmi_from_assignment``."""
    from unified_eval import evaluate_nmi_from_assignment
    return evaluate_nmi_from_assignment(labels, assignment)


def run_one(method_name: str, fn, dataset: str, seed: int) -> dict[str, Any]:
    """Run one (method, dataset, seed) cell. Mirrors experiments/run_tier1_protocol.py:run_one."""
    t0 = time.time()
    try:
        res = fn(dataset, seed=seed, epochs=EPOCHS)
        runtime = time.time() - t0
        return {
            "method": method_name,
            "dataset": dataset,
            "seed": seed,
            "nmi": res["nmi"],
            "ari": res["ari"],
            "fmi": res["fmi"],
            "homo": res["homo"],
            "compl": res["compl"],
            "v_measure": res["v_measure"],
            "runtime_s": runtime,
        }
    except Exception as exc:
        runtime = time.time() - t0
        print(f"  [{method_name:>10} on {dataset:<12} seed={seed}] FAIL: "
              f"{type(exc).__name__}: {exc}", file=sys.stderr)
        return {
            "method": method_name,
            "dataset": dataset,
            "seed": seed,
            "nmi": float("nan"),
            "ari": float("nan"),
            "fmi": float("nan"),
            "homo": float("nan"),
            "compl": float("nan"),
            "v_measure": float("nan"),
            "runtime_s": runtime,
        }


def _print_summary(rows: list[dict[str, Any]]) -> None:
    """Mean NMI per (method, dataset) table — same layout as paper §5.1."""
    import numpy as np

    print("\n=== Mean NMI per (method, dataset) across 5 seeds ===")
    by_pair: dict[tuple[str, str], list[float]] = {}
    for r in rows:
        if not np.isnan(r["nmi"]):
            by_pair.setdefault((r["method"], r["dataset"]), []).append(r["nmi"])

    # Header
    header = ["Method".ljust(10)] + [d.ljust(10) for d in DATASETS] + ["Mean".rjust(7)]
    print("  ".join(header))
    print("  ".join(["-" * 10] * (len(DATASETS) + 2)))
    for m in TIER1_KEYS:
        row = [m.ljust(10)]
        means = []
        for d in DATASETS:
            vals = by_pair.get((m, d), [])
            if vals:
                mean = float(np.mean(vals))
                row.append(f"{mean:.3f}".ljust(10))
                means.append(mean)
            else:
                row.append("—".ljust(10))
        row.append(f"{np.mean(means):.3f}".rjust(7) if means else "—".rjust(7))
        print("  ".join(row))
    print()
    print(f"Wrote {len(rows)} rows to {OUT_CSV}")


# ---------------------------------------------------------------- main ----
def main() -> None:
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    total = len(TIER1_KEYS) * len(DATASETS) * len(SEEDS)
    print(f"=== 5-seed Tier-1 baseline reproduction: "
          f"{len(TIER1_KEYS)} baselines × {len(DATASETS)} datasets × "
          f"{len(SEEDS)} seeds = {total} runs ===")
    print(f"  Output CSV: {OUT_CSV}")
    print(f"  Wrappers from: {_EXPERIMENTS / 'baselines_official.py'}")
    print(f"  Cloned repos used: /home/woody/workspace/ARC/baselines/vGraph/")

    rows: list[dict[str, Any]] = []
    done = 0
    t_global = time.time()
    for dataset in DATASETS:
        for seed in SEEDS:
            for name in TIER1_KEYS:
                _, fn = BASELINE_REGISTRY[name]
                done += 1
                row = run_one(name, fn, dataset, seed)
                rows.append(row)
                # Incremental save (matches run_tier1_protocol.py:78-79)
                with OUT_CSV.open("w", newline="") as f:
                    w = csv.DictWriter(f, fieldnames=CSV_COLUMNS)
                    w.writeheader()
                    w.writerows(rows)
                if not (isinstance(row["nmi"], float) and row["nmi"] != row["nmi"]):  # not NaN
                    elapsed = time.time() - t_global
                    rate = done / elapsed
                    eta_min = (total - done) / max(rate, 1e-9) / 60.0
                    print(f"  [{done:3d}/{total}] {name:>10} on {dataset:<12} "
                          f"seed={seed} NMI={row['nmi']:.4f} "
                          f"({row['runtime_s']:.1f}s) "
                          f"rate={rate:.2f}/s ETA={eta_min:.1f} min")
    elapsed = time.time() - t_global
    print(f"\n=== DONE: {done} runs in {elapsed/60:.1f} min ===")
    _print_summary(rows)


if __name__ == "__main__":
    main()